ignore_merge_commits = true
branch_whitelist = [ "master" ]
skip_untracked = false
tag_prefix = "v"
post_bump_hooks = [
  "git push",
  "git push origin v{{version}}"
]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e

echo "[Check current commit message]"
cog verify --file $1

echo "[Conventional commit check]"
cog check
"""

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "BossRush2024"
owner = "oknozor"

authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
]

